name: Docker Build And Push To Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: sheadmin/dev1
          
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dev1:va
          
      -
        name: Run ssh command 
        env:
          SSH_USER: ${{ secrets.REMOTE_USER }}
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SSH_HOST: ${{ secrets.REMOTE_HOST }}
        
        run: docker ps 'docker-compose restart'
      - 
        name: Check docker 
        run: docker-compose restart 'docker restart'
        
        
