name: Docker Build And Push To Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  
          
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dev1:va
          
      -
        name: Run ssh command 
        id: ssh
        uses: arthurvanl/action-exec-ssh@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          password: ${{ secrets.SERVER_SSH_KEY }}
          ssh_1: df -h
          ssh_2: docker ps
          #ssh_3: '<SSH_COMMAND>'
          #ssh_4: '<SSH_COMMAND>'
        
        
